name: Build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          java-version: 1.8

      - name: Set up JDK env
        uses: actions/setup-java@v4.2.1

      - name: Run Unit Tests
        run: ./gradlew testStagingDebugUnitTest

